idf_component_register(SRCS 
                       "dimmer.c"
                       "encoder.c"
                       "led.c"
                       "pwm.c"
                       "shared.c"
                       "strap.c"
                       "wifi.c"
                       INCLUDE_DIRS "include")
